{
  "hash": "23292779cdb5ca2f715edbd6717d0438",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"STAT 801A Lab 3: Inference About a Single Mean\"\nauthor: \"Insert Name\"\ndate: today\nformat: html\neditor: visual\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\n# Inference About a Single Mean\n\nIn previous work, the parameters for our probability distributions were assumed to be known. Real data does not typically come with its parameters attached, so we must estimate them from the data we do have. We have a sample, and we want to say something about the population it came from. That is inference.\n\nTwo questions drive this lab:\n\n- Confidence intervals: what values of $\\mu$ are consistent with our data?\n\n- Hypothesis tests: is our data consistent with a specific claim about $\\mu$?\n\nThroughout this lab we will assume $\\sigma$ is known.\n\n## Notation\n\n| Symbol    | Meaning                                | Known?                    |\n|-----------|----------------------------------------|---------------------------|\n| $\\mu$     | population mean                        | No. This is what we want. |\n| $\\sigma$  | population standard deviation          | Yes, assumed known        |\n| $\\bar{y}$ | sample mean                            | Yes                       |\n| $n$       | sample size                            | Yes                       |\n| $\\mu_0$   | the value of $\\mu$ a hypothesis claims | Yes, it is given          |\n\n## The sampling distribution of $\\bar{y}$\n\nTake a sample, calculate $\\bar{y}$. Take another, get a different number. The sample mean is itself a random variable with a distribution.\n\n$$\\bar{y} \\sim N\\left(\\mu, \\frac{\\sigma^2}{n}\\right)$$\n\nIts standard deviation is called the standard error.\n\n$$SE = \\frac{\\sigma}{\\sqrt{n}}$$\n\n------------------------------------------------------------------------\n\n# Confidence Intervals\n\nThe sample mean $\\bar{y}$ is a point estimate of $\\mu$. But a point estimate on its own says nothing about how precise it is, and $\\bar{y}$ is almost certainly not exactly $\\mu$. A confidence interval reports a range of plausible values instead of a single number.\n\n## The formula\n\n$$\\bar{y} \\pm z_{\\alpha/2} \\frac{\\sigma}{\\sqrt{n}}$$\n\nThe critical value comes from the standard normal. Calling `qnorm` with no `mean` or `sd` gives $N(0, 1)$.\n\nNote: a 95% interval puts 2.5% in each tail, so use `qnorm(0.975)`, not `qnorm(0.95)`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.975)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.95) # 90% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.644854\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.995) # 99% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.575829\n```\n\n\n:::\n:::\n\n\n## Computing one in R\n\nA machine fills bags of coffee with a target weight of 340 grams. The population standard deviation is known to be 2 grams. An inspector weighs 20 bags.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweights <- c(338.1, 341.2, 339.5, 342.0, 337.8, 340.6, 336.9, 343.1,\n             339.9, 338.4, 341.7, 340.2, 337.5, 342.8, 339.1, 340.8,\n             338.6, 341.4, 336.2, 340.0)\n\nn <- length(weights)\nybar <- mean(weights)\nsigma <- 2\n\nn\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20\n```\n\n\n:::\n\n```{.r .cell-code}\nybar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 339.79\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse <- sigma / sqrt(n)\ncrit <- qnorm(0.975)\nmargin <- crit * se\n```\n:::\n\n\nCalculate interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nybar - margin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 338.9135\n```\n\n\n:::\n\n```{.r .cell-code}\nybar + margin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 340.6665\n```\n\n\n:::\n:::\n\n\nWe are 95% confident the true mean fill weight is between 338.91 and 340.67 grams.\n\n## What 95% confidence means\n\nThe interval either contains $\\mu$ or it does not. Once the data is collected there is no probability about it.\n\nThe 95% describes the procedure, not this one interval: if we repeated the whole process many times, about 95% of the intervals would contain $\\mu$.\n\n## Simulating 100 confidence intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20211)\n\nybars <- replicate(100, mean(rnorm(30, mean = 340, sd = 2)))\n\nmargin <- qnorm(0.975) * 2 / sqrt(30)\n\nci <- data.frame(sample_id = 1:100,\n                 lower = ybars - margin,\n                 upper = ybars + margin)\n\nci$contains <- ci$lower <= 340 & ci$upper >= 340\nmean(ci$contains)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.96\n```\n\n\n:::\n:::\n\n\n96 of the 100 simulated confidence intervals include the real value for $\\mu$. This number will be close to 95% every time the simulation is run.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ci, aes(x = sample_id, ymin = lower, ymax = upper, color = contains)) +\n  geom_errorbar() +\n  geom_hline(yintercept = 340, linewidth = 1) +\n  labs(x = \"Sample\", y = \"95% confidence interval\", color = \"Contains mu\")\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nNote: every interval has the same width, since $\\sigma$ and $n$ never change. Only the center moves. An interval misses when its sample mean lands too far from $\\mu$.\n\n------------------------------------------------------------------------\n\n# Hypothesis Testing\n\n$H_0$ -\\> the null hypothesis, the claim we assume is true\n\n$H_a$ -\\> the alternative hypothesis, what we would like to test\n\nFor a single mean the null always has this form.\n\n$$H_0: \\mu = \\mu_0$$\n\nThe alternative takes one of three forms, depending on the question being asked.\n\n$$H_a: \\mu \\neq \\mu_0 \\qquad H_a: \\mu < \\mu_0 \\qquad H_a: \\mu > \\mu_0$$\n\n## The Null Distribution\n\nThe null distribution tells us what to expect when $H_0$ is true. Everything in a hypothesis test is a comparison against it. The rejection region is its most extreme 5%.\n\nWe can build it by simulation -\\> pretend the null is true, draw many samples from it, and look at the results.\n\nThe machine is supposed to average 340 grams, with $\\sigma$ known to be 2. We take samples of 36 bags.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu0 <- 340\nsigma <- 2\nn <- 36\n\n\nybars <- replicate(5000, mean(rnorm(n, mean = mu0, sd = sigma)))\n\nsim_y <- data.frame(ybar = ybars)\n\nhead(sim_y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ybar\n1 339.7215\n2 339.9766\n3 339.7522\n4 340.1893\n5 339.6982\n6 340.5904\n```\n\n\n:::\n:::\n\n\nEach value in sim_y is the mean of one simulated sample of 36 bags, assuming the null hypothesis is true.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse <- sigma / sqrt(n)\n\nlower_cut <- mu0 - qnorm(0.975) * se\nupper_cut <- mu0 + qnorm(0.975) * se\n\nlower_cut\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 339.3467\n```\n\n\n:::\n\n```{.r .cell-code}\nupper_cut\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 340.6533\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheory_y <- data.frame(x = seq(339, 341, length.out = 500))\ntheory_y$density <- dnorm(theory_y$x, mean = mu0, sd = se)\n\nggplot(sim_y, aes(x = ybar)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50,\n                 fill = \"lightblue\", color = \"black\") +\n  geom_line(data = theory_y, aes(x = x, y = density),\n            linewidth = 1, inherit.aes = FALSE) +\n  geom_vline(xintercept = c(lower_cut, upper_cut), linetype = \"dashed\") +\n  labs(x = \"Sample mean (grams)\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe simulated sample means follow the theoretical curve $N(\\mu_0, \\sigma^2 / n)$.\n\n## The test statistic\n\n$$z = \\frac{\\bar{y} - \\mu_0}{\\sigma / \\sqrt{n}}$$\n\nThe numerator is how far our sample mean sits from the null. The denominator is the standard error.\n\nSo z answers: how many standard errors is our sample mean from the null value?\n\nWhen $H_0$ is true, this statistic follows the standard normal.\n\n$$z \\sim N(0, 1)$$\n\n## Rejection regions\n\nThe machine is supposed to average 340 grams, with $\\sigma$ known to be 2. A sample of 36 bags averages 339.1. Test at $\\alpha = 0.05$ whether the machine is off target.\n\n$$H_0: \\mu = 340 \\qquad H_a: \\mu \\neq 340$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu0 <- 340\nsigma <- 2\nn <- 36\nybar <- 339.1\n\nz <- (ybar - mu0) / (sigma / sqrt(n))\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.7\n```\n\n\n:::\n:::\n\n\nThe rejection region is the set of test statistics extreme enough to reject. A two-tailed test at $\\alpha = 0.05$ splits the 5% between both tails.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.959964\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.975)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n\nWe reject if $z < -1.96$ or $z > 1.96$. Our z is -2.7, so we reject $H_0$ and conclude the machine is off target.\n\n## The null distribution on the z scale\n\nStandardizing every simulated sample mean turns the picture above into the null distribution of $z$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSE <- sigma / sqrt(n)\n\nz_stats <- replicate(1000, (mean(rnorm(n, mean = mu0, sd = sigma)) - mu0) / SE)\n\nsim <- data.frame(z = z_stats)\n\nhead(sim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            z\n1  0.36167355\n2  0.91216797\n3  1.12192657\n4 -0.61906779\n5 -0.40803310\n6 -0.04951538\n```\n\n\n:::\n:::\n\n\nSame simulation, same samples, different scale. The center is now 0 and the cutoffs are $\\pm 1.96$ no matter what the data measures. Different problems will have different data scales, standardizing puts them all on the same one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheory <- data.frame(x = seq(-4, 4, length.out = 500))\ntheory$density <- dnorm(theory$x)\n\nggplot(sim, aes(x = z)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50,\n                 fill = \"lightblue\", color = \"black\") +\n  geom_line(data = theory, aes(x = x, y = density),\n            linewidth = 1, inherit.aes = FALSE) +\n  geom_vline(xintercept = c(-1.96, 1.96), linetype = \"dashed\") +\n  labs(x = \"z statistic\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab3_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(abs(z_stats) > 1.96)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.048\n```\n\n\n:::\n:::\n\n\nAbout 5% of simulated z statistics under the null hypothesis fall inside the rejection region. That is what $\\alpha$ means: the proportion of times we reject a null that was actually true. This is also known as a type 1 error.\n\n## p-values\n\nThe rejection region gives a yes or no. A p-value reports how extreme the data was: the probability, assuming $H_0$ is true, of a test statistic at least as extreme as ours.\n\nTwo-tailed, so we take both tails.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2 * pnorm(abs(z), lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.006933948\n```\n\n\n:::\n:::\n\n\nSince 0.0069 \\< 0.05, we reject the null\n\n## One-tailed tests\n\nIf only one direction matters, the alternative points one way.\n\n$$H_0: \\mu = 340 \\qquad H_a: \\mu < 340$$\n\nAll 5% goes into the lower tail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.644854\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003466974\n```\n\n\n:::\n:::\n\n\nNote: the one-tailed critical value is closer to zero, which makes rejecting easier\n\n| Alternative | Critical value at $\\alpha = 0.05$ | p-value in R |\n|----|----|----|\n| $\\mu \\neq \\mu_0$ | $\\pm$ `qnorm(0.975)` | `2 * pnorm(abs(z), lower.tail = FALSE)` |\n| $\\mu < \\mu_0$ | `qnorm(0.05)` | `pnorm(z)` |\n| $\\mu > \\mu_0$ | `qnorm(0.95)` | `pnorm(z, lower.tail = FALSE)` |\n\n## Writing a z-score function\n\nR has no built-in z test, so this is a good place to write our own function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_c <- function(y, mu = 0, sigma = 1) {\n  \n  # Remove missing values\n  count_missing <- sum(is.na(y))\n  message(paste('Number of missing observations that are excluded:', count_missing))\n  \n  y <- y[!is.na(y)]\n  \n  # Compute from data\n  ybar <- mean(y)\n  n <- length(y)\n  \n  # Compute test statistic\n  test_statistic <- (ybar - mu) / (sigma / sqrt(n))\n  \n  # Return value\n  return(test_statistic)\n}\n```\n:::\n\n\nRun it on the coffee weights against a null value of 340\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweights <- c(338.1, 341.2, 339.5, 342.0, 337.8, 340.6, 336.9, 343.1,\n             339.9, 338.4, 341.7, 340.2, 337.5, 342.8, 339.1, 340.8,\n             338.6, 341.4, 336.2, 340.0)\n\nz_c(weights, mu = 340, sigma = 2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNumber of missing observations that are excluded: 0\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.4695743\n```\n\n\n:::\n:::\n\n\nThe sample mean of 339.79 sits less than half a standard error below the target\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_coffee <- z_c(weights, mu = 340, sigma = 2)  \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNumber of missing observations that are excluded: 0\n```\n\n\n:::\n\n```{.r .cell-code}\n2 * pnorm(abs(z_coffee), lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6386592\n```\n\n\n:::\n:::\n\n\nLarge p-value, so we do not reject. This matches the confidence interval from earlier, which contained 340. A 95% interval and a two-tailed test at α=0.05 always agree\n\n# Practice Problems\n\nAnswer each question in the code chunk provided. Where a problem asks for hypotheses, write them in LaTeX.\n\n## Problem 1:\n\n> A sample of 25 batteries has a mean lifetime of 487 hours. The population standard deviation is known to be 45 hours.\n\n\\(a\\) Compute the standard error.\n\n\n::: {.cell}\n\n:::\n\n\n\\(b\\) Find the critical value for a 95% confidence interval.\n\n\n::: {.cell}\n\n:::\n\n\n\\(c\\) Construct the 95% confidence interval.\n\n\n::: {.cell}\n\n:::\n\n\n\\(d\\) Interpret the interval in a sentence.\n\nWe are 95% confident....\n\n\\(e\\) Build a 99% interval. Is it wider or narrower, and why?\n\n\n::: {.cell}\n\n:::\n\n\n## Problem 2:\n\n> A machine fills bags with a target of 340 grams, $\\sigma$ known to be 4. A sample of 36 bags averages 338.5. Test at $\\alpha = 0.05$ whether the mean has shifted.\n\n\\(a\\) State the hypotheses.\n\n$$H_0: \\mu   \\qquad H_a: \\mu $$\n\n\\(b\\) Compute the test statistic.\n\n\n::: {.cell}\n\n:::\n\n\n\\(c\\) Find the rejection region.\n\n\n::: {.cell}\n\n:::\n\n\n\\(d\\) Is the test statistic in the rejection region? State your conclusion.\n\n\\(e\\) Compute the p-value and confirm it gives the same conclusion.\n\n\n::: {.cell}\n\n:::\n\n\n## Problem 3:\n\n> A trainer claims a new program raises mean vertical jump above 24 inches. Fifteen athletes are measured, with $\\sigma$ known to be 1.2 inches.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njumps <- c(25.1, 23.8, 26.2, 24.9, 25.5, 22.9, 26.8, 24.2,\n           25.9, 23.6, 27.1, 25.3, 24.7, 26.4, 25.0)\n```\n:::\n\n\n\\(a\\) State the hypotheses. This is a one-tailed test.\n\n$$H_0: \\mu  \\qquad H_a: \\mu $$\n\n\\(b\\) Compute the sample mean and the standard error.\n\n\n::: {.cell}\n\n:::\n\n\n\\(c\\) Compute the test statistic.\n\n\n::: {.cell}\n\n:::\n\n\n\\(d\\) Find the critical value at $\\alpha = 0.05$ and state your conclusion.\n\n\n::: {.cell}\n\n:::\n\n\n\\(e\\) Compute the one-tailed p-value.\n\n\n::: {.cell}\n\n:::\n\n\n\\(f\\) Build a 95% confidence interval for the mean vertical jump.\n\n\n::: {.cell}\n\n:::\n\n\n# Final Step\n\nRender your document. Click the Render button at the top of the editor, or press Ctrl + Shift + K.\n\nIf the render fails, read the error message. It names the chunk that caused the problem. The most common causes are a missing closing parenthesis, or an object used before it was created.\n",
    "supporting": [
      "STAT_801A_Lab3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}