{
  "hash": "6d6dfbc65c7e06fdc8d75e2f25463de6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Project 1 Solutions\"\nformat: html\n---\n\n# Problem 1\n\nRead in the data and print the first 10 observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nne_work_commute <- read.csv(\"travel-time-31109.csv\")\nhead(ne_work_commute, n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   RESPONDENT TRANTIME DEPARTS ARRIVES\n1           1        7     647     654\n2           2        8    1305    1309\n3           3       10    1445    1454\n4           4       10    1605    1614\n5           5       10    1605    1614\n6           6       15    1515    1534\n7           7       15    1435    1449\n8           8        7    1545    1554\n9           9       12    1535    1544\n10         10       15    1435    1449\n```\n\n\n:::\n:::\n\n\n\n# Problem 2\n\nUse `dim()` to determine the dimensions of the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(ne_work_commute)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 861   4\n```\n\n\n:::\n:::\n\n\nThe dataset contains 861 rows and 4 columns.\n\n# Problem 3\n\nCompute the mean of `TRANTIME`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(ne_work_commute$TRANTIME)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.34727\n```\n\n\n:::\n:::\n\n\nThe mean travel time is 18.35 minutes.\n\n# Problem 4\n\nCompute the median of `TRANTIME`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(ne_work_commute$TRANTIME)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15\n```\n\n\n:::\n:::\n\n\nThe median travel time is 15 minutes.\n\n# Problem 5\n\nCompute the variance of `TRANTIME`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(ne_work_commute$TRANTIME)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 193.3293\n```\n\n\n:::\n:::\n\n\nThe variance of travel time is 193.33 minutes squared.\n\nVariance measures the amount of variability in travel time using squared deviations from the mean.\n\n# Problem 6\n\nCompute the standard deviation of `TRANTIME`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(ne_work_commute$TRANTIME)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.90429\n```\n\n\n:::\n:::\n\n\nThe standard deviation of travel time is 13.9 minutes.\n\n# Problem 7\n\nUse `summary()` on `TRANTIME`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ne_work_commute$TRANTIME)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1.00   10.00   15.00   18.35   20.00  129.00 \n```\n\n\n:::\n:::\n\n\nThe values returned by `summary()` have the following interpretations:\n\n- **Minimum:** The smallest observed travel time.\n- **1st Quartile:** The value below which approximately 25% of observations fall.\n- **Median:** The middle travel time.\n- **Mean:** The arithmetic average travel time.\n- **3rd Quartile:** The value below which approximately 75% of observations fall.\n- **Maximum:** The largest observed travel time.\n\n# Problem 8\n\nCreate a histogram of `TRANTIME`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(\n  ne_work_commute$TRANTIME,\n  main = \"Distribution of Travel Time to Work\",\n  xlab = \"Travel Time (minutes)\",\n  ylab = \"Number of Respondents\"\n)\n```\n\n::: {.cell-output-display}\n![](project1-solutions_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe data is right-skewed with large outliers.\n\n# Problem 9\n\nWould the mean or median be a better description of travel time?\n\nThe median would be a better description since there are large values that would increase the mean.\n\n# Problem 10\n\nCreate `filtered_travel_time` by removing outliers using the IQR method.\n\nAn observation is considered an outlier if\n\n$$\nx < Q_1 - 1.5(IQR)\n$$\n\nor\n\n$$\nx > Q_3 + 1.5(IQR).\n$$\n\nFirst calculate the quartiles and IQR.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nne_summary <- summary(ne_work_commute$TRANTIME)\n\niqr <- IQR(ne_work_commute$TRANTIME)\n\nq1 <- as.numeric(ne_summary[2])\nq3 <- as.numeric(ne_summary[5])\niqr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\nCalculate the lower and upper boundaries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlower_bound <- q1 - 1.5 * iqr\nupper_bound <- q3 + 1.5 * iqr\n\nlower_bound\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -5\n```\n\n\n:::\n\n```{.r .cell-code}\nupper_bound\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 35\n```\n\n\n:::\n:::\n\n\nNow retain only observations within these boundaries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_travel_time <- ne_work_commute$TRANTIME[\n  ne_work_commute$TRANTIME >= lower_bound &\n  ne_work_commute$TRANTIME <= upper_bound\n]\n```\n:::\n\n\n\n# Problem 11\n\nCreate a histogram of `filtered_travel_time`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(\n  filtered_travel_time,\n  main = \"Travel Time to Work After Removing Outliers\",\n  xlab = \"Travel Time (minutes)\",\n  ylab = \"Number of Respondents\"\n)\n```\n\n::: {.cell-output-display}\n![](project1-solutions_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nAfter removing the outliers, the data is somewhat symmetrical with some right-skew.\n\n# Problem 12\n\nRepeat Problems 3–6 using `filtered_travel_time` and arrange the results into a formatted table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_summary <- data.frame(\n  Statistic = c(\n    \"Mean\",\n    \"Median\",\n    \"Variance\",\n    \"Standard Deviation\"\n  ),\n  Value = c(\n    mean(filtered_travel_time),\n    median(filtered_travel_time),\n    var(filtered_travel_time),\n    sd(filtered_travel_time)\n  )\n)\n\nknitr::kable(\n  filtered_summary,\n  digits = 2,\n  col.names = c(\"Statistic\", \"Value\"),\n  caption = \"Summary Statistics After Removing Outliers\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary Statistics After Removing Outliers\n\n|Statistic          | Value|\n|:------------------|-----:|\n|Mean               | 16.24|\n|Median             | 15.00|\n|Variance           | 54.74|\n|Standard Deviation |  7.40|\n\n\n:::\n:::\n\n\n\n# Problem 13\n\nDescribe what changed after removing the outliers.\n\nCalculate the original and filtered summary statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noriginal_stats <- c(\n  Mean = mean(ne_work_commute$TRANTIME),\n  Median = median(ne_work_commute$TRANTIME),\n  Variance = var(ne_work_commute$TRANTIME),\n  SD = sd(ne_work_commute$TRANTIME)\n)\n\nfiltered_stats <- c(\n  Mean = mean(filtered_travel_time),\n  Median = median(filtered_travel_time),\n  Variance = var(filtered_travel_time),\n  SD = sd(filtered_travel_time)\n)\n\nrbind(\n  Original = original_stats,\n  Filtered = filtered_stats\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Mean Median  Variance        SD\nOriginal 18.34727     15 193.32926 13.904289\nFiltered 16.23601     15  54.74082  7.398704\n```\n\n\n:::\n:::\n\n\nThe median stayed the same. The mean slightly decreased, and the variance / standard deviation greatly decreased.\n\n# Problem 14\n\nLet $X$ be normally distributed with the mean and variance calculated from `filtered_travel_time`.\n\nThus,\n\n$$\nX \\sim N(\\mu,\\sigma^2),\n$$\n\nwhere $\\mu$ and $\\sigma^2$ are the mean and variance of `filtered_travel_time`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- mean(filtered_travel_time)\nsigma <- sd(filtered_travel_time)\n\nmu\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16.23601\n```\n\n\n:::\n\n```{.r .cell-code}\nsigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.398704\n```\n\n\n:::\n:::\n\n\nNote that `pnorm()` requires the **standard deviation**, not the variance, so `sigma` is supplied to the `sd` argument.\n\n## (a) Probability of less than 10 minutes\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_less_10 <- pnorm(\n  10,\n  mean = mu,\n  sd = sigma\n)\n\np_less_10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1996557\n```\n\n\n:::\n:::\n\n\n\n## (b) Probability of between 10 and 20 minutes\n\nWe want\n\n$$\nP(10 < X < 20).\n$$\n\nUsing cumulative probabilities,\n\n$$\nP(10 < X < 20)\n=\nP(X < 20)-P(X < 10).\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_10_20 <- pnorm(\n  20,\n  mean = mu,\n  sd = sigma\n) -\n  pnorm(\n    10,\n    mean = mu,\n    sd = sigma\n  )\n\np_10_20\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4948758\n```\n\n\n:::\n:::\n\n\n## (c) Probability of greater than 20 minutes\n\nWe want\n\n$$\nP(X > 20).\n$$\n\nUsing the complement,\n\n$$\nP(X > 20)=1-P(X\\leq20).\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_greater_20 <- 1 - pnorm(\n  20,\n  mean = mu,\n  sd = sigma\n)\n\np_greater_20\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3054685\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "project1-solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}