{
  "hash": "79f2c15002eb8a15266cf6b18bd0b80c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"STAT 801A Lab 2: Quarto and Probability Distributions\"\nauthor: \"Insert Name\"\ndate: today\nformat: \n  html:\n    number-sections: false\neditor: visual\nexecute:\n  warning: false\n---\n\n# Quarto\n\nAn R script (.R) holds only code. A Quarto document (.qmd) holds code, output, and writing in one file. You \"render\" the file and Quarto runs every piece of R code, captures the results, and stitches everything into a finished HTML page, PDF, or Word document.\n\nTo learn more about Quarto see <https://quarto.org>.\n\n## Text Formatting\n\n\\# Level 1 heading\n\n\\## Level 2 heading\n\n\\### Level 3 heading (and so on)\n\n\\*italic\\* and \\*\\*bold\\*\\* and \\`code style\\`\n\n\\- bullet point\n\n1\\. numbered item\n\n2\\. another item\n\nMake sure to leave a blank line between paragraphs. Two paragraphs jammed together with no blank line will render as one.\n\n## Code chunks\n\nWe can run normal R code with code chunks. You can insert one with `Ctrl + Alt + I` (`command + option + I` on macOS) or you can insert one manually\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2 + 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n:::\n\n\n### Chunk options\n\nOptions go inside the chunk on lines starting with `#|`. The space after `#|` is required.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(c(82, 91, 76, 88, 95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 86.4\n```\n\n\n:::\n:::\n\n\n## Inline code\n\nTo drop a computed number into a sentence, use `r \"code\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscores <- c(82, 91, 76, 88, 95)\n```\n:::\n\n\nThe mean score was 86.4\n\n## Rendering\n\nClick the **Render** button at the top of the editor (or press `Ctrl + Shift + K`). RStudio saves the file, runs all the code from top to bottom in a fresh R session, and opens the result in whatever format is specified\n\n# Math Equations with LaTeX\n\nQuarto renders mathematical notation using LaTeX syntax.\n\n## Symbol reference\n\n| You want | You type | Result |\n|------------------------|------------------------|------------------------|\n| Greek letters | `$\\mu$ $\\sigma$ $\\lambda$ $\\alpha$ $\\beta$` | $\\mu$ $\\sigma$ $\\lambda$ $\\alpha$ $\\beta$ |\n| Capital Greek | `$\\Sigma$ $\\Delta$ $\\Phi$` | $\\Sigma$ $\\Delta$ $\\Phi$ |\n| Subscript | `$x_1$` and `$x_{10}$` | $x_1$ and $x_{10}$ |\n| Superscript | `$x^2$` and `$e^{-\\lambda}$` | $x^2$ and $e^{-\\lambda}$ |\n| Fraction | `$\\frac{a}{b}$` | $\\frac{a}{b}$ |\n| Square root | `$\\sqrt{x}$` and `$\\sqrt[3]{x}$` | $\\sqrt{x}$ and $\\sqrt[3]{x}$ |\n| Summation | `$\\sum_{i=1}^{n} x_i$` | $\\sum_{i=1}^{n} x_i$ |\n| Product | `$\\prod_{i=1}^{n} x_i$` | $\\prod_{i=1}^{n} x_i$ |\n| Integral | `$\\int_{-\\infty}^{\\infty} f(x)\\,dx$` | $\\int_{-\\infty}^{\\infty} f(x)\\,dx$ |\n| Binomial coefficient | `$\\binom{n}{k}$` | $\\binom{n}{k}$ |\n| Bar / hat | `$\\bar{x}$` and `$\\hat{p}$` | $\\bar{x}$ and $\\hat{p}$ |\n| Inequalities | `$\\leq$ $\\geq$ $\\neq$ $\\approx$` | $\\leq$ $\\geq$ $\\neq$ $\\approx$ |\n| Plus/minus | `$\\pm$` | $\\pm$ |\n| Distributed as | `$X \\sim N(\\mu, \\sigma^2)$` | $X \\sim N(\\mu, \\sigma^2)$ |\n\nWrap math in single dollar signs to put it in a sentence, or double dollar signs to put it on its own centered line.\n\n# ggplot2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"ggplot2)\nlibrary(ggplot2)\n```\n:::\n\n\nEvery ggplot needs three things, and layers are joined with a +:\n\n1.  Data - a data frame.\n2.  Aesthetic mapping - which column goes on which axis, written inside aes().\n3.  A geom - what type of plot is drawn\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mtcars, aes(x = wt, y = mpg)) + geom_point()\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab2_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n## Common geoms\n\n| Geom             | Draws                      | Typically needs |\n|------------------|----------------------------|-----------------|\n| geom_point()     | Scatterplot                | x and y         |\n| geom_line()      | Connected line             | x and y         |\n| geom_col()       | Bars at heights you supply | x and y         |\n| geom_histogram() | Histogram                  | x only          |\n| geom_boxplot()   | Boxplot                    | x and y         |\n| geom_smooth()    | Trend line                 | x and y         |\n\n## Labels and themes\n\nlabs() sets the title and axis labels. A theme\\_\\*() function changes the overall look.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mtcars, aes(x = wt, y = mpg)) + \n  geom_point() +\n  labs(x = \"Weight\",y = \"Miles per Gallon\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Mapping color vs. setting color\n\nInside aes(), a color is mapped to a variable, so it changes from point to point and a legend appears\n\nOutside aes(), a color is set to one fixed value for everything\n\nGenerally, if the appearance should depend on the data, it goes inside aes(). If it is just a style choice you are making, it goes outside.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n ggplot(data = mtcars, aes(x = mpg)) + \n   geom_histogram(bins=10,color = \"black\",fill=\"lightblue\")\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab2_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mtcars, aes(x = wt, y = mpg, color = factor(cyl))) + \n  geom_point() +\n  labs(x = \"Weight\",y = \"Miles per Gallon\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n# Probability Distributions in R\n\nA **probability distribution** is a rule that tells you how likely each possible outcome is.\n\nDiscrete:\n\n- Binomial - Number of successes in a fixed number of trials\n\n- Poisson - Count of events occurring in a fixed interval of time or space\n\nContinuous\n\n- Normal - Continuous distribution with a symmetric, bell-shaped curve\n\nWhen we assume a random variable follows a particular probability distribution, we can calculate the probability that the random variable takes a particular value or falls within a particular range of values.\n\n| Wording                                                  | Distribution |\n|----------------------------------------------------------|--------------|\n| \"out of 20 coin flips,\" \"12 questions,\" \"10 free throws\" | Binomial     |\n| \"what proportion of trials succeed\"                      | Binomial     |\n| \"an average of 4.5 per hour,\" \"3.2 per month\"            | Poisson      |\n| \"how many arrive,\" \"how many occur\"                      | Poisson      |\n| \"normally distributed,\" \"bell-shaped\"                    | Normal       |\n| \"mean of 500 hours with a standard deviation of 45\"      | Normal       |\n\n## Notation\n\nYou will see distributions written in shorthand. The symbol $\\sim$ is read as \"is distributed as.\" The letter $X$ stands for the thing you are counting or measuring.\n\nBinomial: $X \\sim \\text{Bin}(n, p)$\n\n\"X is distributed binomial with $n$ trials and success probability $p$.\"\n\nPoisson: $X \\sim \\text{Pois}(\\lambda)$\n\nRead: \"X is distributed Poisson with rate $\\lambda$.\"\n\nNormal: $X \\sim N(\\mu, \\sigma^2)$\n\nRead: \"X is distributed normal with mean $\\mu$ and variance $\\sigma^2$.\n\n| Distribution | Parameters      | Meaning                                  |\n|--------------|-----------------|------------------------------------------|\n| Binomial     | $n$, $p$        | number of trials, probability of success |\n| Poisson      | $\\lambda$       | average number of events per interval    |\n| Normal       | $\\mu$, $\\sigma$ | mean, standard deviation                 |\n\nOnce we identify the parameters of interest, we can use R to make our lives easier when using these distributions\n\n## How R names these functions\n\nR uses a naming system: a prefix describing what you want, plus a root naming the distribution.\n\nThe roots:\n\n| Distribution | Root  |\n|--------------|-------|\n| Binomial     | binom |\n| Poisson      | pois  |\n| Normal       | norm  |\n\nThe prefixes:\n\n| Prefix | What it gives you                                           |\n|--------|-------------------------------------------------------------|\n| d      | the probability of exactly one specific value               |\n| p      | the probability of that value or anything smaller           |\n| q      | works backwards: you give a probability, it returns a value |\n| r      | random values drawn from the distribution                   |\n\nCombine the prefix and distribution to get functions:\n\n|     | Binomial | Poisson | Normal |\n|-----|----------|---------|--------|\n| d   | dbinom   | dpois   | dnorm  |\n| p   | pbinom   | ppois   | pnorm  |\n| q   | qbinom   | qpois   | qnorm  |\n| r   | rbinom   | rpois   | rnorm  |\n\n------------------------------------------------------------------------\n\n## The Binomial distribution\n\nA quiz has 12 multiple-choice questions, each with 4 options. A student guesses randomly on every question.\n\n$$X \\sim \\text{Bin}(12, 0.25)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 12\np <- 0.25\n```\n:::\n\n\n### dbinom - exactly one value\n\nQuestion: What is the probability the student gets exactly 5 correct?\n\nIn symbols: $P(X = 5)$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(5, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1032414\n```\n\n\n:::\n:::\n\n\nThere is about a 10.3% chance of getting exactly 5 correct.\n\nNote: R uses \"size\" and \"prob\" arguments rather than \"n\" and \"p\"\n\nYou can ask for several values at once. Giving 0:12 returns the probability of every possible outcome. This gives us the probability distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(0:12, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 3.167635e-02 1.267054e-01 2.322932e-01 2.581036e-01 1.935777e-01\n [6] 1.032414e-01 4.014945e-02 1.147127e-02 2.389848e-03 3.540516e-04\n[11] 3.540516e-05 2.145767e-06 5.960464e-08\n```\n\n\n:::\n:::\n\n\n### pbinom - a value or anything smaller\n\nQuestion: What is the probability the student gets 3 or fewer correct?\n\nIn symbols: $P(X \\leq 3)$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(3, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6487786\n```\n\n\n:::\n:::\n\n\nThis will yield the same result:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dbinom(0:3, size = n, prob = p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6487786\n```\n\n\n:::\n:::\n\n\n### Going the other direction\n\nQuestion: What is the probability of getting at least 6 correct?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pbinom(5, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05440223\n```\n\n\n:::\n:::\n\n\nR has a shortcut for this. Adding lower.tail = FALSE as an argument flips the direction.\n\nNOTE: When lower.tail = FALSE is used, R calculates the probability of values greater than the number specified. It does not include the specified number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(5, size = n, prob = p, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05440223\n```\n\n\n:::\n:::\n\n\nThis will calculate the probability getting 6 or more questions correct\n\n### Seeing the distribution\n\nPlotting dbinom for every outcome shows the shape\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom_df <- data.frame(x = 0:12)\nbinom_df$prob <- dbinom(binom_df$x, size = n, prob = p)\n\nggplot(binom_df, aes(x = x, y = prob)) +\n  geom_col(fill = \"lightblue\") +\n  labs( x = \"Number correct\", y = \"P(X = x)\") \n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab2_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n### qbinom and rbinom\n\nqbinom runs backwards. Give it a probability and it returns the value\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqbinom(0.90, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\nThat says 90% of guessing students score 5 or fewer.\n\nrbinom simulates. Here are 1000 imaginary students taking the quiz\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#set.seed(90210)\n\nquizzes <- data.frame(correct = rbinom(1000, size = n, prob = p))\n\nggplot(quizzes, aes(x = correct)) +\n  geom_bar(fill = \"lightblue\") +\n  labs(x = \"Number correct\", y = \"Number of students\")\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab2_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## The Poisson distribution\n\nThe parameter, $\\lambda$ (lambda), the average number of events per interval.\n\n> A campus help line receives an average of 4 calls per hour.\n\n$$X \\sim \\text{Pois}(4)$$\n\nNote: lambda = 4 is the expected number of calls in ONE hour. If you want the number of calls in a workday (8 hours), you must multiply by 8 to get that distribution: lambda = 32.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda <- 4\n```\n:::\n\n\n### dpois - exactly one value\n\nQuestion: What is the probability of exactly 3 calls in an hour?\n\nIn symbols: $P(X = 3)$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(3, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1953668\n```\n\n\n:::\n:::\n\n\nAbout a 19.5% chance of exactly 3 calls\n\n### ppois - a value or anything smaller\n\nQuestion: What is the probability of 2 or fewer calls?\n\nIn symbols: $P(X \\leq 2)$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppois(2, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2381033\n```\n\n\n:::\n:::\n\n\nQuestion: What is the probability of more than 6 calls?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppois(6, lambda = lambda, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.110674\n```\n\n\n:::\n:::\n\n\n### Seeing the distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\npois_df <- data.frame(k = 0:15)\npois_df$prob <- dpois(pois_df$k, lambda = lambda)\n\nggplot(pois_df, aes(x = k, y = prob)) +\n  geom_col(fill = \"darkorange\") +\n  labs(x = \"Number of calls\",y = \"P(X = k)\")\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab2_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n### qpois and rpois\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqpois(0.95, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(801)\ncalls <- rpois(1000, lambda = lambda)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## The Normal distribution\n\nThe normal takes two parameters, the mean $\\mu$ and the variance $\\sigma^2$. In R these are the arguments mean and sd.\n\nNote: sd is the standard deviation, not the variance. If a problem tells you the variance is 25, you must take the square root and pass sd = 5\n\n### What changes for a continuous distribution\n\nBecause a measurement can land on any value, the probability of hitting one exact number is zero. $P(X = 70)$ is 0\n\nTwo consequences:\n\n- Every normal question is about a range, never a single value.\n\n- dnorm is not a probability. It's only the height of the curve, useful for drawing\n\n> Adult male heights are approximately normal with a mean of 70 inches and a standard deviation of 3 inches.\n\n$$X \\sim N(70, 9)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- 70\nsigma <- 3\n```\n:::\n\n\n### pnorm - the area to the left\n\nQuestion: What proportion of men are shorter than 66 inches?\n\nIn symbols: $P(X < 66)$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(66, mean = mu, sd = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09121122\n```\n\n\n:::\n:::\n\n\nAnswer: About 9% of men are shorter than 66 inches.\n\nQuestion: What proportion are taller than 74 inches?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(74, mean = mu, sd = sigma, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09121122\n```\n\n\n:::\n:::\n\n\nQuestion: What proportion are between 66 and 74 inches?\n\nTake everything below 74 and subtract off everything below 66. What remains is everything between 74 and 66\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(74, mean = mu, sd = sigma) - pnorm(66, mean = mu, sd = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8175776\n```\n\n\n:::\n:::\n\n\n### Seeing the distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve_df <- data.frame(x = seq(58, 82, length.out = 1000))\ncurve_df$density <- dnorm(curve_df$x, mean = mu, sd = sigma)\n\nggplot(curve_df, aes(x = x, y = density)) +\n  geom_line(linewidth=1) +\n  geom_area(data = subset(curve_df, x <= 66), fill = \"lightblue\") +\n  labs(x = \"Height (inches)\",y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](STAT_801A_Lab2_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n### qnorm - going backwards from a probability\n\nQuestion: How tall is a man at the 90th percentile?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.90, mean = mu, sd = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 73.84465\n```\n\n\n:::\n:::\n\n\nAnswer: A man at the 90th percentile is about 73.8 inches tall.\n\n### rnorm - simulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheights <- rnorm(1000, mean = mu, sd = sigma)\n\nmean(heights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70.03411\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(heights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.901656\n```\n\n\n:::\n:::\n\n\nThe mean and sd of the simulated normal distribution are very close to the true parameters\n\n# Practice Problems\n\nAnswer each question in the code chunk provided. Where a problem asks you to state a distribution, write it in LaTeX using the notation from the lab.\n\n## Problem 1:\n\n> A seed company claims 85% of its seeds germinate. A gardener plants 20 seeds. Let $X$ be the number that germinate.\n\n(a) State the distribution of $X$.\n\n$$X \\sim$$\n\n(b) What is the probability that exactly 18 seeds germinate?\n\n\n::: {.cell}\n\n:::\n\n\n(c) What is the probability that at least 18 germinate?\n\n\n::: {.cell}\n\n:::\n\n\n(d) What is the probability that 15 or fewer germinate?\n\n\n::: {.cell}\n\n:::\n\n\n(e) What is the probability that between 16 and 19 germinate?\n\n\n::: {.cell}\n\n:::\n\n\n(f) Use ggplot2 to make a bar plot of the distribution.\n\n\n::: {.cell}\n\n:::\n\n\n## Problem 2:\n\n> A busy intersection averages 3.2 accidents per month.\n\n(a) State the distribution of the monthly accident count $X$\n\n$$X \\sim$$\n\n(b) What is the probability of exactly 5 accidents in a month?\n\n\n::: {.cell}\n\n:::\n\n\n(c) What is the probability of no accidents in a month?\n\n\n::: {.cell}\n\n:::\n\n\n(d) What is the probability of at least 4 accidents in a month?\n\n\n::: {.cell}\n\n:::\n\n\n(e) What is the probability of more than 40 accidents in a year? Remember to rescale $\\lambda$\n\n\n::: {.cell}\n\n:::\n\n\n(f) The city wants enough emergency response capacity to handle the monthly accident count in 99% of months. What number should they plan for? (Hint: you are finding a value, not a probability)\n\n\n::: {.cell}\n\n:::\n\n\n(g) Use ggplot2 to make a plot of the distribution\n\n\n::: {.cell}\n\n:::\n\n\n## Problem 3:\n\n> A manufacturer's batteries last an average of 500 hours with a standard deviation of 45 hours, and battery life is approximately normally distributed.\n\n(a) State the distribution of battery life $X$.\n\n$$X \\sim$$\n\n(b) What is the probability a battery lasts less than 425 hours?\n\n\n::: {.cell}\n\n:::\n\n\n(c) What is the probability a battery lasts more than 560 hours?\n\n\n::: {.cell}\n\n:::\n\n\n(d) What proportion of batteries last between 450 and 550 hours?\n\n\n::: {.cell}\n\n:::\n\n\n(e) The company will replace the shortest-lasting 2% of batteries under warranty. What lifetime should the warranty cover?\n\n\n::: {.cell}\n\n:::\n\n\n(f) Use ggplot2 to plot the distribution of battery life. (Hint: build a data frame of x values from 350 to 650, use dnorm for the curve height, and draw it with geom_line.)\n\n\n::: {.cell}\n\n:::\n\n\n## Problem 4: Choosing the right distribution\n\nFor each scenario, name the distribution and compute the requested probability.\n\n(a) A basketball player makes 78% of her free throws. She shoots 10 in a game. What is the probability she makes exactly 9?\n\n\n::: {.cell}\n\n:::\n\n\n(b) A website receives an average of 12 visits per minute. What is the probability it receives fewer than 8 visits in a given minute?\n\n\n::: {.cell}\n\n:::\n\n\n(c) Scores on a standardized exam are normally distributed with a mean of 1050 and a variance of 40000. What score is at the 75th percentile?\n\n\n::: {.cell}\n\n:::\n\n\n# Final Step\n\nRender your document. Click the Render button at the top of the editor, or press Ctrl + Shift + K.\n\nIf the render fails, read the error message. It names the chunk that caused the problem. The most common causes are a missing closing parenthesis, or an object was used before it was created.\n",
    "supporting": [
      "STAT_801A_Lab2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}