project: 
  type: website
  resources:
    - notes/
  render:
    - '!reka/'
    - '!erin/'
    - '*.qmd'

website:
  title: "STAT 801A"
  navbar:
    left:
      - href: index.qmd
        text: Course Home
      - href: canvas.qmd
        text: Canvas
      - href: assignments.qmd
        text: Assignments
      - href: notes.qmd
        text: Notes
        
format: 
  html:
    theme: flatly
    toc: true
    
execute:
  freeze: true