project: 
  type: website
  output-dir: docs
  resources:
    - notes/
    - labs/
    - "*.xlsx"
    - "*.csv"
    - "projects/project1/project1-LastName-FirstName.qmd"
  render:
    - '!reka/'
    - '!erin/'
    - '*.qmd'
    - '!stat-801-class-examples/'

website:
  title: "STAT 801A"
  navbar:
    left:
      - href: canvas.qmd
        text: Canvas
      - href: assignments.qmd
        text: Assignments
      - href: notes.qmd
        text: Notes
        
format: 
  html:
    theme: flatly
    toc: true
    
execute:
  freeze: true