---
title: Inferences about $\mu$
subtitle: "Confidence Intervals, Type I and II Errors, p-value, t-distribution"
footer: STAT 801A
format: 
  revealjs:
    smaller: true
    incremental: false
---


## Inferences about $\mu$

One of the major objectives of statistics is to make inferences about the distribution of the elements in a [*population*]{style="color: magenta"} based on information contained in a [*sample*]{style="color: magenta"}.

- Numerical summaries that characterize the population distribution are called [*parameters*]{style="color: magenta"}. 

- We will first focus on the [*population mean*]{style="color: magenta"} $\mu$ and [*population variance*]{style="color: magenta"} $\sigma^2$

## Inferences about $\mu$

Two main types of questions:

1. Estimation: what is the value of the parameter?

\
\
\

2. Test a hypothesis: how does the parameter compare to some value?

## Estimation of $\mu$

The [*point estimate*]{style="color: magenta"} of $\mu$ is

\
\
\
\
\

## Confidence Interval for $\mu$

An interval estimate, called a [*confidence interval*]{style="color: magenta"}, incorporates information about the amount of sampling error in $\bar{y}$

- A [confidence interval]{style="color: magenta"} for $\mu$ takes the form 

## Confidence Interval for $\mu$

Recall the CLT, where $(\bar{Y}-\mu)/(\sigma\sqrt{n})\sim N(0,1)$. Let $Z\sim N(0,1)$ and $z_{\alpha/2}$ denote the quantile of a standard normal distribution such that $P(Z>z)=\alpha/2$, $0\lt\alpha\lt 1$.

\
\
\

The following is a $(1-\alpha/2)100$% confidence interval:


## Confidence Interval for $\mu$

We can rewrite the following statement to put the interval around $\mu$.

$P(-z_{\alpha/2}\leq\frac{(\bar{Y}-\mu)}{\sigma/\sqrt{n}}\leq z_{\alpha/2})=$



## Confidence Interval for $\mu$

Since $\bar{Y}$ is random, [*it is not correct to say that the interval*]{style="color: magenta"} $(\bar{y} - \frac{\sigma}{\sqrt{n}} \, z_{\alpha/2},\bar{y} + \frac{\sigma}{\sqrt{n}} \, z_{\alpha/2})$ [*contains $\mu$ with a specified probability*]{style="color: magenta"}. If samples are repeatedly taken from the population, $(1-\alpha/2)100$% of the intervals would contain the true parameter. 

- In a future lab, we will examine this property through simulation.
- It is usually written in the form $$\left( \bar{y} - \frac{\sigma}{\sqrt{n}} \, z_{\alpha/2}, \
           \bar{y} + \frac{\sigma}{\sqrt{n}} \, z_{\alpha/2}\right) \ .$$

"We are $(1-\alpha/2)100$% confident that the parameter ... *context* ... is between LCL and UCL."

## How do we get $z_{\alpha/2}$?

- Reference a Z-table (example: <https://archive.math.arizona.edu/rsims/ma464/standardnormaltable.pdf>)
- Use R

```{r}
#| include: true
#| echo: true
alpha <- 0.05
z <- qnorm(1-alpha/2)
print(z)
```

- By default, `qnorm()` measures $P(Z\leq z)$ when $Z\sim N(0,1)$. $Z_{\alpha/2}$ refers to the area under the curve when $Z\sim N(0,1)$. 

## Notes

- As the confidence coefficient increases the confidence interval becomes wider. A wider interval estimates $\mu$ less precisely. Thus a 99% confidence interval is [less accurate]{style="color: magenta"} than a 95% confidence interval but one has [more confidence]{style="color: magenta"} that $\mu$ is in the first interval.

- Also note that increasing the sample size $n$ results in a narrower interval (more accurate estimate) for the same confidence coefficient.

## Example:

The caffeine content (in mg) was examined for a random sample of 50 cups of black coffee dispensed by a new machine. The mean and standard deviation were 110 mg and 7.1 mg, respectively. Use these data to construct a 98% confidence interval for $\mu$, the mean caffeine content for cups dispensed by the machine.


## Example - cont.

$\left[\bar{y} - z_{0.01} \frac{\sigma}{\sqrt{n}}, \
\bar{y} + z_{0.01} \frac{\sigma}{\sqrt{n}}\right]$\

\

$\left[110 - (2.33)\left(\frac{7.1}{\sqrt{50}}\right), \
   110 + (2.33)\left(\frac{7.1}{\sqrt{50}}\right)  \right]$\

\

$(107.66,\ 112.34)$\

\

We are $98\%$ confident that the mean caffeine content for cups dispensed by the machine is between 107.66 and 112.34 mg.

## Hypothesis Testing

A [Null Hypothesis]{style="color: magenta"} [$H_0$]{style="color: red"} describes a characteristic of the population (it is believed to be) as it currently exists
  
\
\
\


A [Research Hypothesis]{style="color: magenta"} (or [Alternative Hypothesis]{style="color: magenta"}) [$H_a$]{style="color: red"}, which is a proposal about this characteristic, by the person(s) conducting the statistical study.

\
\
\

The idea is that the null hypothesis is presumed to hold unless there is overwhelming evidence in the data in support of the research hypothesis.

## Example

- To determine whether the mean yield per acre (in bushels), $\mu$, of a variety of soybeans increased the current year over the last two years when $\mu$ is believed to be 520 bushels per acre, the following might be tested. $$H_0: \mu \leq 520 \ \ \ \mbox{vs.}\ \ \ H_a: \mu > 520$$

- The fact that $\mu$ may equal a specific value is always included in the null hypothesis. The decision to state whether the data supports the research hypothesis or not is based on a quantity computed from the data called the [test statistic]{style="color: magenta"}.

---

If $\bar{y}$ is in the rejection region then reject $H_0$ and say the evidence favors $H_a$.
