{
  "hash": "4820e5a63fe26f5b27b0eb87f7e36ce3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Project 2 Solutions\"\nformat: html\n---\n\n# Problem 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz.test <- function(y, mu = 0, sigma = 1,\n                   alternative = c('two.sided', 'less', 'greater'),\n                   conf.level = 0.95) {\n  \n  alternative <- match.arg(alternative)\n  message(paste('Number of missing values:', sum(is.na(y))))\n  y_orig <- y\n  y <- y[!is.na(y)]\n  # Calculations here\n  xbar <- mean(y)\n  n <- length(y)\n  se <- sigma / sqrt(n)\n  z <- (xbar-mu)/se\n  alpha <- 1-conf.level\n  \n  # Hypothesis tests\n  if(alternative == \"two.sided\") {\n    lcl <- xbar - qnorm(1-alpha/2)*se\n    ucl <- xbar + qnorm(1-alpha/2)*se\n    p.value <- 2*pnorm(abs(z), lower.tail = F)\n  } else if (alternative == 'less') {\n    lcl <- -Inf\n    ucl <- xbar + qnorm(1-alpha)*se\n    p.value <- pnorm(z)\n  } else if (alternative == 'greater') {\n    lcl <- xbar - qnorm(1-alpha)*se\n    ucl <- Inf\n    p.value <- pnorm(z, lower.tail = FALSE)\n  } else {\n    stop(\"Invalid alternative provided\")\n  }\n  \n  \n  # Organize results\n  results <- list(\n    data = y_orig,                                      # Original data\n    sample_mean = xbar,                                # Mean of the data\n    standard_error = se,                             # Standard error\n    z = z,                                          # Test statistic\n    parameters = list(mu = mu, sigma = sigma),     # Parameters        \n    alternative = alternative,                     # The alternative hypothesis\n    alpha = alpha,                                      # Significance level\n    confidence_interval = list(lcl = lcl, ucl = ucl),    # Confidence interval\n    p.value = p.value                                     # p-value of the test\n    \n  )\n  \n  # Output list of results\n  return(results)\n}\n```\n:::\n\n\n# Problem 2\n\n## Part a\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz.test.data <- read.csv('z-test-data.csv')\nz.test(y=z.test.data$prob2a,\n       mu=30, sigma=sd(z.test.data$prob2a),\n       alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNumber of missing values: 0\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n [1] 31.3 28.8 31.0 29.8 28.8 33.6 29.5 35.6 29.8 37.4 34.1 36.3 34.9 36.4 32.7\n[16] 34.2 33.8 29.4 31.7 28.2 26.5 30.0 35.3 32.1 32.5 30.7 34.4 32.3 30.3 32.6\n[31] 29.5 32.8 38.9 31.1 31.1 24.2 26.5 30.8 29.1 31.5\n\n$sample_mean\n[1] 31.7375\n\n$standard_error\n[1] 0.4895404\n\n$z\n[1] 3.549247\n\n$parameters\n$parameters$mu\n[1] 30\n\n$parameters$sigma\n[1] 3.096126\n\n\n$alternative\n[1] \"greater\"\n\n$alpha\n[1] 0.05\n\n$confidence_interval\n$confidence_interval$lcl\n[1] 30.93228\n\n$confidence_interval$ucl\n[1] Inf\n\n\n$p.value\n[1] 0.0001931671\n```\n\n\n:::\n:::\n\n\nThe p-value is less than 0.05, meaning that we reject the null hypothesis. There is evidence to conclude that the true mean is greater than 30. \n\n## Part b\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz.test(y=z.test.data$prob2b,\n       mu=15, sigma=sd(z.test.data$prob2b),\n       alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNumber of missing values: 0\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n [1] 19.8 18.4  7.6 14.3 15.8 10.7 13.0 11.1 10.2 18.5 14.4 13.6  5.6 15.4 19.4\n[16] 17.9 12.4 21.8 18.8 23.1  8.8 22.8  8.5  8.0 20.1 15.9 14.5 21.6 20.3 14.5\n[31] 15.0 12.0 12.0 14.5 13.0 14.6  8.6  8.0 21.1  5.5\n\n$sample_mean\n[1] 14.5275\n\n$standard_error\n[1] 0.7744062\n\n$z\n[1] -0.6101449\n\n$parameters\n$parameters$mu\n[1] 15\n\n$parameters$sigma\n[1] 4.897775\n\n\n$alternative\n[1] \"less\"\n\n$alpha\n[1] 0.05\n\n$confidence_interval\n$confidence_interval$lcl\n[1] -Inf\n\n$confidence_interval$ucl\n[1] 15.80128\n\n\n$p.value\n[1] 0.2708829\n```\n\n\n:::\n:::\n\n\nThe p-value is greater than 0.05, meaning that we fail to reject the null hypothesis. There is not evidence to conclude that the true mean is less than 15. \n\n## Part c\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz.test(y=z.test.data$prob2c,\n       mu=50, sigma=sd(z.test.data$prob2c),\n       alternative = 'two.sided')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNumber of missing values: 0\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n [1] 55.9 55.5 55.2 61.7 46.5 59.9 53.9 52.5 54.0 53.4 54.9 55.5 59.4 55.8 56.7\n[16] 48.1 52.0 54.3 61.2 54.2 49.7 57.5 60.1 51.5 50.1 53.2 52.7 54.7 60.7 48.3\n[31] 51.1 51.3 55.4 59.0 59.3 54.0 54.8 52.2 46.9 52.0\n\n$sample_mean\n[1] 54.3775\n\n$standard_error\n[1] 0.6132876\n\n$z\n[1] 7.137761\n\n$parameters\n$parameters$mu\n[1] 50\n\n$parameters$sigma\n[1] 3.878771\n\n\n$alternative\n[1] \"two.sided\"\n\n$alpha\n[1] 0.05\n\n$confidence_interval\n$confidence_interval$lcl\n[1] 53.17548\n\n$confidence_interval$ucl\n[1] 55.57952\n\n\n$p.value\n[1] 9.486344e-13\n```\n\n\n:::\n:::\n\n\nThe p-value is less than 0.05, meaning that we reject the null hypothesis. There is evidence to conclude that the true mean is different from 50. \n\n# Problem 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmn_river <- read.csv('mn-river-n-samples.csv')\ny <- mn_river$N_mg_l\nqqnorm(y); qqline(y)\n```\n\n::: {.cell-output-display}\n![](project2-solutions_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(y)\n```\n\n::: {.cell-output-display}\n![](project2-solutions_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(y)\n```\n\n::: {.cell-output-display}\n![](project2-solutions_files/figure-html/unnamed-chunk-5-3.png){width=672}\n:::\n:::\n\n\nFor the part, values tend to follow the line in the Q-Q plot. The histogram shows a little bit of skewness, but nothing out of the ordinary. The boxplot looks fairly symmetrical. The data appears to be approximately normally distributed.\n\n# Problem 4\n\n$$\nH_0: \\mu=4.19\n$$\n\n$$\nH_0: \\mu>4.19\n$$\n\n# Problem 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove missing values\ny <- y[!is.na(y)]\n\n# Calculate necessary values\nn <- length(y)\nxbar <- mean(y)\nalpha <- 0.05\nse <- sd(y)/sqrt(n)\n\ntest_statistic <- (xbar-4.19)/se\np_value <- pt(test_statistic, df = n-1, lower.tail = F)\nci <- xbar + c(-1,1)*qt(p=1-alpha, df=n-1)*se\nknitr::kable(data.frame(\n  test_statistic = test_statistic,\n  p_value = p_value,\n  lower_cl = ci[1],\n  upper_cl = Inf\n))\n```\n\n::: {.cell-output-display}\n\n\n| test_statistic|   p_value| lower_cl| upper_cl|\n|--------------:|---------:|--------:|--------:|\n|       2.030372| 0.0261377| 4.201277|      Inf|\n\n\n:::\n:::\n\n\n\n# Problem 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x=y, alternative = 'greater', mu = 4.19)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  y\nt = 2.0304, df = 27, p-value = 0.02614\nalternative hypothesis: true mean is greater than 4.19\n95 percent confidence interval:\n 4.201277      Inf\nsample estimates:\nmean of x \n     4.26 \n```\n\n\n:::\n:::\n\n\n\n# Problem 7\n\nThe results of (5) and (6) are the same, but (6) is in a more structured format. \n\n\n# Problem 8\n\nThere is evidence to conclude that the true average Nitrogen (in mg/L) in the Minnesota River is greater than the previous historical average of 0.19 (p-value=0.02614). With 95% confidence, the true average quantity of Nitrogen is greater than 4.201 mg/L.\n\n",
    "supporting": [
      "project2-solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}